var textData = [
	{
		title: 'testTitle',
		lauch: 'January',
		category: 'development',
		preview: {
			type: 'image',
			src: 'images/works/deki2_42.jpg',
		},
		src: 'images/works/deki2_42.jpg',
		link: 'works.html',
	},
	{
		title: 'testTitle',
		lauch: 'January',
		category: 'development',
		preview: {
			type: 'image',
			src: 'images/works/deki2_41.jpg',
		},
		src: 'images/works/deki2_41.jpg',
		link: 'works.html',
	},
	{
		title: 'testTitle',
		lauch: 'January',
		category: 'development',
		preview: {
			type: 'image',
			src: 'images/works/deki2_40.jpg',
		},
		src: 'images/works/deki2_40.jpg',
		link: 'works.html',
	},
	{
		title: 'testTitle',
		lauch: 'January',
		category: 'development',
		preview: {
			type: 'image',
			src: 'images/works/deki2_39.jpg',
		},
		src: 'images/works/deki2_39.jpg',
		link: 'works.html',
	},
	{
		title: 'testTitle',
		lauch: 'January',
		category: 'development',
		preview: {
			type: 'image',
			src: 'images/works/deki2_38.jpg',
		},
		src: 'images/works/deki2_38.jpg',
		link: 'works.html',
	},
	{
		title: 'testTitle',
		lauch: 'January',
		category: 'development',
		preview: {
			type: 'image',
			src: 'images/works/deki2_37.jpg',
		},
		src: 'images/works/deki2_37.jpg',
		link: 'works.html',
	},
	{
		title: 'testTitle',
		lauch: 'January',
		category: 'development',
		preview: {
			type: 'image',
			src: 'images/works/deki2_36.jpg',
		},
		src: 'images/works/deki2_36.jpg',
		link: 'works.html',
	},
	{
		title: 'testTitle',
		lauch: 'January',
		category: 'development',
		preview: {
			type: 'image',
			src: 'images/works/deki2_35.jpg',
		},
		src: 'images/works/deki2_35.jpg',
		link: 'works.html',
	},
	{
		title: 'testTitle',
		lauch: 'January',
		category: 'development',
		preview: {
			type: 'image',
			src: 'images/works/deki2_34.jpg',
		},
		src: 'images/works/deki2_34.jpg',
		link: 'works.html',
	},
	{
		title: 'testTitle',
		lauch: 'January',
		category: 'development',
		preview: {
			type: 'image',
			src: 'images/works/deki2_33.jpg',
		},
		src: 'images/works/deki2_33.jpg',
		link: 'works.html',
	},
	{
		title: 'testTitle',
		lauch: 'January',
		category: 'development',
		preview: {
			type: 'image',
			src: 'images/works/deki2_32.jpg',
		},
		src: 'images/works/deki2_32.jpg',
		link: 'works.html',
	},
	{
		title: 'testTitle',
		lauch: 'January',
		category: 'development',
		preview: {
			type: 'image',
			src: 'images/works/deki2_31.jpg',
		},
		src: 'images/works/deki2_31.jpg',
		link: 'works.html',
	},
	{
		title: 'testTitle',
		lauch: 'January',
		category: 'development',
		preview: {
			type: 'image',
			src: 'images/works/deki2_30.jpg',
		},
		src: 'images/works/deki2_30.jpg',
		link: 'works.html',
	},
	{
		title: 'testTitle',
		lauch: 'January',
		category: 'development',
		preview: {
			type: 'image',
			src: 'images/works/deki2_29.jpg',
		},
		src: 'images/works/deki2_29.jpg',
		link: 'works.html',
	},
	{
		title: 'testTitle',
		lauch: 'January',
		category: 'development',
		preview: {
			type: 'image',
			src: 'images/works/deki2_28.jpg',
		},
		src: 'images/works/deki2_28.jpg',
		link: 'works.html',
	},
	{
		title: 'testTitle',
		lauch: 'January',
		category: 'development',
		preview: {
			type: 'image',
			src: 'images/works/deki2_27.jpg',
		},
		src: 'images/works/deki2_27.jpg',
		link: 'works.html',
	},
	{
		title: 'testTitle',
		lauch: 'January',
		category: 'development',
		preview: {
			type: 'image',
			src: 'images/works/deki2_26.jpg',
		},
		src: 'images/works/deki2_26.jpg',
		link: 'works.html',
	},
	{
		title: 'testTitle',
		lauch: 'January',
		category: 'development',
		preview: {
			type: 'image',
			src: 'images/works/deki2_25.jpg',
		},
		src: 'images/works/deki2_25.jpg',
		link: 'works.html',
	},
	{
		title: 'testTitle',
		lauch: 'January',
		category: 'development',
		preview: {
			type: 'image',
			src: 'images/works/deki2_21.jpg',
		},
		src: 'images/works/deki2_21.jpg',
		link: 'works.html',
	},
	{
		title: 'testTitle',
		lauch: 'January',
		category: 'development',
		preview: {
			type: 'image',
			src: 'images/works/deki2_22.jpg',
		},
		src: 'images/works/deki2_22.jpg',
		link: 'works.html',
	},
	{
		title: 'testTitle',
		lauch: 'January',
		category: 'development',
		preview: {
			type: 'image',
			src: 'images/works/deki2_23.jpg',
		},
		src: 'images/works/deki2_23.jpg',
		link: 'works.html',
	},
	{
		title: 'testTitle',
		lauch: 'January',
		category: 'development',
		preview: {
			type: 'image',
			src: 'images/works/deki2_24.jpg',
		},
		src: 'images/works/deki2_24.jpg',
		link: 'works.html',
	},
	{
		title: 'testTitle',
		lauch: 'January',
		category: 'development',
		preview: {
			type: 'image',
			src: 'images/works/deki2_2.jpg',
		},
		src: 'images/works/deki2_2.jpg',
		link: 'works.html',
	},
	{
		title: 'testTitle',
		lauch: 'January',
		category: 'development',
		preview: {
			type: 'image',
			src: 'images/works/deki2_4.jpg',
		},
		src: 'images/works/deki2_4.jpg',
		link: 'works.html',
	},
	{
		title: 'testTitle',
		lauch: 'January',
		category: 'development',
		preview: {
			type: 'image',
			src: 'images/works/deki2_6.jpg',
		},
		src: 'images/works/deki2_6.jpg',
		link: 'works.html',
	},
	{
		title: 'testTitle',
		lauch: 'January',
		category: 'development',
		preview: {
			type: 'image',
			src: 'images/works/deki2_8.jpg',
		},
		src: 'images/works/deki2_8.jpg',
		link: 'works.html',
	},
	{
		title: 'testTitle',
		lauch: 'January',
		category: 'development',
		preview: {
			type: 'image',
			src: 'images/works/victas_iamnext_03.jpg',
		},
		src: 'images/works/victas_iamnext_03.jpg',
		link: 'works.html',
	},
	{
		title: 'testTitle',
		lauch: 'January',
		category: 'development',
		preview: {
			type: 'image',
			src: 'images/works/iamnext.jpg',
		},
		src: 'images/works/iamnext.jpg',
		link: 'works.html',
	},
];
