version: "3.2"

networks:
  main:
    driver: bridge
    attachable: true

services:
  db:
    image: mysql:latest
    container_name: cartube_mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_DATABASE=ringerdb
      - MYSQL_USER=mirehiko
      - MYSQL_PASSWORD=sorellina
      - MYSQL_ROOT_PASSWORD=sorellina
    networks:
      - main
    volumes:
      - "./volumes/mysql/db:/var/lib/mysql"

  web:
    build:
      context: ./build/
    container_name: cartube_web
    environment:
      - VIRTUAL_HOST=car-tube.ru
    volumes:
      - "./build/ringo:/ringo"
      - "./volumes/static:/ringo/static"
      - "./volumes/media:/media"
    depends_on:
      - db
    links:
      - db
    networks:
      - main

  nginx:
    image: nginx:latest
    container_name: cartube_nginx
    volumes:
      - "./volumes/nginx/conf.d:/etc/nginx/conf.d"
      - "./volumes/media:/media:ro"
      - "./volumes/static:/ringo/static:ro"
    depends_on:
      - web
    ports:
      - 80:80
    networks:
      - main

  node:
    build:
      context: ./build/node
    container_name: cartube_node
    volumes:
      - "./build/ringo/works/static:/static"
      - "./build/ringo/works/static-dev:/static-dev"
      - "./build/node:/app"
