version: '3.2'

networks:
  main:
    driver: bridge
    attachable: true


services:
  db: 
    image: mysql:latest
    restart: always
    container_name: cartube_mysql
    command: --default-authentication-plugin=mysql_native_password
    environment: 
      - MYSQL_DATABASE=ringerdb
      - MYSQL_USER=mirehiko
      - MYSQL_PASSWORD=sorellina
      - MYSQL_ROOT_PASSWORD=sorellina
    networks:
      - main

  web:
    build: 
      context: ./build/
    container_name: cartube_web
    restart: always
    environment:
      - VIRTUAL_HOST=car-tube.ru
    volumes:
      # - "./volumes/media:/media"
      # - "./build/ringo:/ringo"
      - "./volumes/mysql/restore_from:/media"
    depends_on:
      - db
    links:
      - db
    networks:
      - main

  nginx:
    image: nginx:latest
    container_name: cartube_nginx
    restart: always
    volumes:
      - "./volumes/nginx/conf.d:/etc/nginx/conf.d"
      # - "./volumes/media:/media"
      - "./volumes/static:/static"
    depends_on:
      - web
    ports:
      - 80:80
    networks:
      - main

  # node:
  #   build:
  #     context: ./build/node
  #   container_name: cartube_node
  #   networks:
  #     - main
  #   volumes:
  #     - "./build/finances/budget/static:/static"
  #     - "./build/node:/app"