# Generated by Django 2.1.7 on 2019-05-23 10:36

from django.db import migrations, models
import django.db.models.deletion
import works.models


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Default',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='', max_length=200, verbose_name='Название сайта')),
                ('site_icon', models.ImageField(blank=True, max_length=255, upload_to=works.models.default_icon, verbose_name='Иконка сайта')),
                ('poster_default', models.ImageField(blank=True, max_length=255, upload_to=works.models.default_poster, verbose_name='Изображение по умолчанию')),
                ('video_preview_default', models.ImageField(blank=True, max_length=255, upload_to=works.models.default_preview, verbose_name='Превью видео по умолчанию')),
            ],
        ),
        migrations.CreateModel(
            name='NewsStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=200, verbose_name='Название')),
            ],
        ),
        migrations.CreateModel(
            name='WorkImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=200, verbose_name='Заголовок')),
                ('url', models.ImageField(blank=True, default='default.jpg', max_length=255, null=True, upload_to='works', verbose_name='Изображение')),
                ('link', models.CharField(blank=True, default='', max_length=500, verbose_name='Внешняя ссылка')),
            ],
        ),
        migrations.CreateModel(
            name='WorkVideo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=200, verbose_name='Название')),
                ('url', models.TextField(default='', max_length=1500, verbose_name='Ссылка на видеофайл')),
                ('preview', models.ImageField(blank=True, max_length=255, null=True, upload_to='works', verbose_name='Превью')),
                ('is_html', models.BooleanField(blank=True, default=False, verbose_name='HTML-код')),
            ],
        ),
        migrations.AddField(
            model_name='category',
            name='category_url',
            field=models.CharField(default='', max_length=200, verbose_name='Ссылка на категорию'),
        ),
        migrations.AddField(
            model_name='work',
            name='poster',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='works', verbose_name='Постер'),
        ),
        migrations.AlterField(
            model_name='category',
            name='category',
            field=models.CharField(default='', max_length=200, verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='news',
            name='description',
            field=models.TextField(blank=True, default='', max_length=500, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='news',
            name='title',
            field=models.CharField(default='', max_length=200, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(default='', max_length=200, verbose_name='Компания'),
        ),
        migrations.AlterField(
            model_name='work',
            name='category',
            field=models.ManyToManyField(blank=True, to='works.Category', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='work',
            name='description',
            field=models.TextField(blank=True, default='', max_length=500, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='work',
            name='launch_date',
            field=models.DateTimeField(verbose_name='Дата запуска'),
        ),
        migrations.AlterField(
            model_name='work',
            name='title',
            field=models.CharField(default='', max_length=200, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='work',
            name='user',
            field=models.ManyToManyField(blank=True, to='works.User', verbose_name='Компания'),
        ),
        migrations.AddField(
            model_name='workvideo',
            name='work',
            field=models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, to='works.Work'),
        ),
        migrations.AddField(
            model_name='workimages',
            name='work',
            field=models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, to='works.Work'),
        ),
    ]
