# Generated by Django 2.1.5 on 2019-03-28 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0002_auto_20190318_1908'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=200, verbose_name='Название')),
            ],
        ),
        migrations.AlterField(
            model_name='news',
            name='description',
            field=models.TextField(blank=True, default='', max_length=500, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='work',
            name='description',
            field=models.TextField(blank=True, default='', max_length=500, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='work',
            name='launch_date',
            field=models.DateTimeField(blank=True, verbose_name='Дата запуска'),
        ),
        migrations.AlterField(
            model_name='work',
            name='poster',
            field=models.ImageField(blank=True, default='default.jpg', max_length=255, null=True, upload_to='works', verbose_name='Постер'),
        ),
    ]
