# Generated by Django 2.1.7 on 2019-05-27 06:10

from django.db import migrations, models
import works.models


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0002_auto_20190523_1536'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='poster',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to=works.models.content_file_name, verbose_name='Постер'),
        ),
        migrations.AlterField(
            model_name='workimages',
            name='url',
            field=models.ImageField(blank=True, default='default.jpg', max_length=255, null=True, upload_to=works.models.content_file_name_related, verbose_name='Изображение'),
        ),

    ]
