# Generated by Django 2.1.7 on 2019-06-08 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0002_auto_20190602_1131'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='link_on_news',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Ссылка на новость'),
        ),
    ]
