# Generated by Django 2.1.7 on 2019-04-01 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0003_auto_20190328_1432'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='launch_date',
            field=models.DateTimeField(verbose_name='Дата запуска'),
        ),
    ]
