# Generated by Django 2.1.7 on 2019-05-27 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0004_auto_20190527_1211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workvideo',
            name='url',
            field=models.TextField(blank=True, default='', max_length=1500, verbose_name='Ссылка на видеофайл'),
        ),
    ]
