# Generated by Django 2.1.7 on 2019-04-04 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0004_auto_20190401_1900'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='category_url',
            field=models.CharField(default='', max_length=200, verbose_name='Ссылка на категорию'),
        ),
    ]
