# Generated by Django 2.1.7 on 2019-04-25 08:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0006_auto_20190404_1726'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=200, verbose_name='Заголовок')),
                ('url', models.ImageField(blank=True, default='default.jpg', max_length=255, null=True, upload_to='works', verbose_name='Постер')),
                ('work', models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, to='works.Work')),
            ],
        ),
    ]
