# Generated by Django 2.1.7 on 2019-04-25 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0008_auto_20190425_1506'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='poster',
            field=models.ImageField(blank=True, default='default.jpg', max_length=255, null=True, upload_to='works', verbose_name='Постер'),
        ),
        migrations.AlterField(
            model_name='workimages',
            name='url',
            field=models.ImageField(blank=True, default='default.jpg', max_length=255, null=True, upload_to='works', verbose_name='Изображение'),
        ),
    ]
