# Generated by Django 2.1.7 on 2019-04-25 11:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0009_auto_20190425_1509'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkVideo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=200, verbose_name='Название')),
                ('url', models.TextField(blank=True, default='', max_length=1500, verbose_name='Ссылка на видео из YouTube')),
                ('is_youtube', models.BooleanField(blank=True, default=False, verbose_name='YouTube видео?')),
                ('is_url', models.BooleanField(blank=True, default=False, verbose_name='Ссылка')),
                ('work', models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, to='works.Work')),
            ],
        ),
    ]
