# Generated by Django 2.1.7 on 2019-04-25 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0010_workvideo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workvideo',
            name='is_youtube',
            field=models.BooleanField(blank=True, default=False, verbose_name='YouTube видео'),
        ),
        migrations.AlterField(
            model_name='workvideo',
            name='url',
            field=models.TextField(blank=True, default='', max_length=1500, verbose_name='Ссылка на видеофайл'),
        ),
    ]
