# Generated by Django 2.1.7 on 2019-04-25 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0011_auto_20190425_1614'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workvideo',
            name='is_url',
        ),
        migrations.RemoveField(
            model_name='workvideo',
            name='is_youtube',
        ),
        migrations.AddField(
            model_name='workvideo',
            name='is_html',
            field=models.BooleanField(blank=True, default=False, verbose_name='HTML-код'),
        ),
    ]
