# Generated by Django 2.1.7 on 2019-04-27 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0012_auto_20190425_1629'),
    ]

    operations = [
        migrations.AddField(
            model_name='workvideo',
            name='poster',
            field=models.ImageField(blank=True, default='default.jpg', max_length=255, null=True, upload_to='works', verbose_name='Превью'),
        ),
    ]
