# Generated by Django 2.1.7 on 2019-04-27 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0013_workvideo_poster'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workvideo',
            old_name='poster',
            new_name='preview',
        ),
    ]
