# Generated by Django 2.1.7 on 2019-05-06 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0014_auto_20190427_2219'),
    ]

    operations = [
        migrations.AddField(
            model_name='workimages',
            name='link',
            field=models.CharField(default='', max_length=500, verbose_name='Внешняя ссылка'),
        ),
    ]
