# Generated by Django 2.1.7 on 2019-05-06 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0015_workimages_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workimages',
            name='link',
            field=models.CharField(blank=True, default='', max_length=500, verbose_name='Внешняя ссылка'),
        ),
        migrations.AlterField(
            model_name='workvideo',
            name='url',
            field=models.TextField(default='', max_length=1500, verbose_name='Ссылка на видеофайл'),
        ),
    ]
