# Generated by Django 2.1.7 on 2019-05-15 09:56

from django.db import migrations, models
import works.models


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0016_auto_20190506_1639'),
    ]

    operations = [

        migrations.AlterField(
            model_name='work',
            name='poster',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='works', verbose_name='Постер'),
        ),
        migrations.AlterField(
            model_name='workvideo',
            name='preview',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='works', verbose_name='Превью'),
        ),
    ]
