# Generated by Django 2.1.7 on 2019-05-14 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0016_auto_20190506_1639'),
    ]

    operations = [
        migrations.CreateModel(
            name='Default',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='', max_length=200, verbose_name='Название сайта')),
                ('site_icon', models.ImageField(default='default.jpg', max_length=255, upload_to='system', verbose_name='Иконка сайта')),
                ('poster_default', models.ImageField(default='default.jpg', max_length=255, upload_to='system', verbose_name='Изображение по умолчанию')),
                ('video_preview_default', models.ImageField(default='default.jpg', max_length=255, upload_to='system', verbose_name='Превью видео по умолчанию')),
            ],
        ),
    ]
