# Generated by Django 2.1.7 on 2019-05-15 08:48

from django.db import migrations, models
import works.models


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0017_default'),
    ]

    operations = [
        migrations.AlterField(
            model_name='default',
            name='poster_default',
            field=models.ImageField(default='default.jpg', max_length=255, upload_to=works.models.default_poster, verbose_name='Изображение по умолчанию'),
        ),
        migrations.AlterField(
            model_name='default',
            name='site_icon',
            field=models.ImageField(default='default.jpg', max_length=255, upload_to=works.models.default_icon, verbose_name='Иконка сайта'),
        ),
        migrations.AlterField(
            model_name='default',
            name='video_preview_default',
            field=models.ImageField(default='default.jpg', max_length=255, upload_to=works.models.default_preview, verbose_name='Превью видео по умолчанию'),
        ),
    ]
